# Generated by Django 4.0.4 on 2022-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaff',
            name='feedback',
            field=models.TextField(),
        ),
    ]
