# Generated by Django 4.0.4 on 2022-06-05 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staffId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
