# Generated by Django 4.0.4 on 2022-06-16 12:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyears',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
