# Generated by Django 4.0.6 on 2022-07-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0002_staff_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
