# Generated by Django 4.0.6 on 2022-07-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0003_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(default='+4073117891', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
