# Generated by Django 4.0.6 on 2022-07-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0004_staff_phone_number_alter_staff_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_text', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolManagementApp.staff')),
            ],
        ),
    ]
