# Generated by Django 4.0.6 on 2022-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0005_stafftodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='address',
            field=models.TextField(default='Adresa1', max_length=500),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(default='+4073117891', max_length=20),
        ),
    ]
