# Generated by Django 4.0.6 on 2022-07-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0007_staff_fcm_token_student_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='sender',
            field=models.TextField(default='Admin'),
        ),
    ]
