# Generated by Django 4.0.6 on 2022-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0008_staffnotification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotification',
            name='sender',
            field=models.TextField(default='Admin'),
        ),
    ]
