# Generated by Django 4.0.6 on 2022-07-21 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0009_studentnotification_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_exam_mark', models.FloatField(default=0)),
                ('subject_assignment_mark', models.FloatField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolManagementApp.student')),
                ('subjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolManagementApp.subject')),
            ],
        ),
    ]
