# Generated by Django 4.0.6 on 2022-08-16 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0010_studentresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresults',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
