# Generated by Django 4.0.6 on 2022-09-24 12:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0011_studentresults_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField(default=0)),
                ('topic', models.CharField(default='', max_length=300)),
                ('join_url', models.CharField(default='', max_length=300)),
                ('password', models.CharField(default='', max_length=300)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolManagementApp.staff')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolManagementApp.subject')),
            ],
        ),
    ]
