# Generated by Django 4.0.6 on 2022-09-24 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0012_zoommeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeting',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
