# Generated by Django 4.0.6 on 2022-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0013_alter_zoommeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeting',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
