# Generated by Django 4.0.6 on 2022-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0014_zoommeting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeting',
            name='meeting_id',
            field=models.IntegerField(default=0),
        ),
    ]
