# Generated by Django 4.0.6 on 2022-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0015_zoommeting_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeting',
            name='meeting_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
