# Generated by Django 4.0.6 on 2022-10-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0016_alter_zoommeting_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
