# Generated by Django 4.0.6 on 2022-11-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagementApp', '0019_remove_student_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresults',
            name='subject_exam_mark',
        ),
    ]
